channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10.18
  - numpy=2.0.2
  - scikit-learn=1.7.1
  - h5py=3.14.0
  - matplotlib=3.10.5
  - tqdm=4.67.1
  - emcee=3.1.6
  - astropy=6.1.7
  - scipy=1.15.3
  - pip=25.2

  - pip:
    - cython==3.1.4
    - pyyaml==6.0.2
    - joblib==1.5.1
    - threadpoolctl==3.6.0
    - getdist==1.7.1
    - tensorflow[and-cuda]==2.19.0
    - tensorflow-probability[tf]==0.25.0